server.port: ${PORT:8761}
spring.profiles.active: single

---

spring:
  profiles: single
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false

---

spring:
  profiles: ha

eureka:
  instance:
    hostname: ${HOSTNAME}
  client:
    serviceUrl:
      defaultZone: ${DEFAULTZONE}


#eureka.client.register-with-eureka: false
#eureka.client.fetch-registry: false