server.port: ${PORT:8761}
spring.profiles.active: single

---

spring:
  profiles: single
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: ha

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${DEFAULTZONE}


#eureka.client.register-with-eureka: false
#eureka.client.fetch-registry: false